In [1]:
import pickle
import numpy as np

train_mean_file = "model_total/data/train_mean.pkl"
test_mean_file = "model_total/data/test_mean.pkl"

train_std_file = "model_total/data/train_std.pkl"
test_std_file = "model_total/data/test_std.pkl"

mean1 = float(pickle.load(open(train_mean_file, "rb")))
mean2 = float(pickle.load(open(test_mean_file, "rb")))

std1 = float(pickle.load(open(train_std_file, "rb")))
std2 = float(pickle.load(open(test_std_file, "rb")))

print(mean1, mean2, std1, std2)

0.21069024503231049 0.2224588245153427 0.7216879725456238 0.7719413638114929


In [2]:
data_norm = data_norm.numpy()

In [3]:
data_norm.shape

(730, 5, 759)

In [5]:
diff = 0
summation = 0
data = data_norm*std + mean

for idx in range(data.shape[2]):
    for store in range(5):
        d = data[:-142, store, idx]
        me = np.median(d)
        for val in d:
            diff += abs(me - val)
            summation += val
            
print(diff, summation, diff / summation)

416450.0005016327 470018.0005016327 0.8860298968489955


In [2]:
import pandas as pd
from pathlib import Path

data_dir = Path('data')

sales_dataframes = []
for year in [2017, 2018]:
    sales_dataframes.append(
        pd.read_csv(
            data_dir / '銷售數量{}.txt'.format(year), sep='\t'
        ).loc[:, ['原始店號', '日期', '商品代號', '銷售數量']]
    )

sales_data = pd.concat(sales_dataframes, axis=0)

print(sales_data)

          原始店號        日期     商品代號  銷售數量
0         1205  20170101  3410025     1
1         1205  20170101  3410025     1
2         1205  20170101  1810792     1
3         1205  20170101  2920637     2
4         1205  20170101  5842614     1
...        ...       ...      ...   ...
1417895  12236  20181231  1720082     1
1417896  12236  20181231  3110180     1
1417897  12236  20181231  6115400     1
1417898  12236  20181231  2710189     1
1417899  12236  20181231  2910367     2

[2814781 rows x 4 columns]


In [9]:
sale_data_agged = sales_data.groupby(['日期', '原始店號', '商品代號'], as_index=True).agg(["sum"])


In [11]:
sale_data_agged
sale_data_agged.index

MultiIndex([(20170101,  1205,  610010),
            (20170101,  1205,  610038),
            (20170101,  1205,  610042),
            (20170101,  1205,  610088),
            (20170101,  1205,  610238),
            (20170101,  1205,  610256),
            (20170101,  1205,  611052),
            (20170101,  1205,  611393),
            (20170101,  1205,  611448),
            (20170101,  1205,  611452),
            ...
            (20181231, 12236, 6138175),
            (20181231, 12236, 6160178),
            (20181231, 12236, 6160423),
            (20181231, 12236, 6160437),
            (20181231, 12236, 6160441),
            (20181231, 12236, 6160946),
            (20181231, 12236, 6160950),
            (20181231, 12236, 6160964),
            (20181231, 12236, 6160978),
            (20181231, 12236, 6160982)],
           names=['日期', '原始店號', '商品代號'], length=1436147)

In [21]:
print(sale_data_agged.loc[20170101,  1205,  610010]['銷售數量', "sum"])

1


In [4]:
import pandas as pd
from pathlib import Path

data_dir = Path('data')
commodity_dataframe = pd.read_csv(data_dir / '商品主檔.txt', sep='\t')


In [27]:
indexed_frame = commodity_dataframe.loc[:, ["商品代號", "原始店號", "品番", "群番"]].set_index(["商品代號", "原始店號"])
indexed_frame.loc[617008, 1205]["品番"]

6

In [5]:
import numpy as np
import torch
a = np.array([1,2,3,4,5,6,7,8,9])
b = torch.tensor(a[:5])
c = torch.tensor(a[3:])

b *= 2
print(b)
print(c)

tensor([ 2,  4,  6,  8, 10], dtype=torch.int32)
tensor([4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [19]:

a = np.array([1,2,3,4,5,6,7,8,9])
b = torch.tensor(a[:5])
c = torch.tensor(a[3:6])
d = torch.tensor(a[4:])

e = torch.cat((b,c,d), 0)
print(e)

tensor([1, 2, 3, 4, 5, 4, 5, 6, 5, 6, 7, 8, 9], dtype=torch.int32)


In [12]:
a, b = divmod(100,3)
print(a, b)

33 1
