In [3]:
import pickle
import torch

In [2]:
sales_data = pickle.load(open("../data/sales_data_pinfan.pkl", "rb"))

In [4]:
x_idx = torch.tensor([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125, 126, 127, 128, 129, 130])
store_idx = 4

In [21]:
sales_data[x_idx, store_idx].transpose(0,1).shape

torch.Size([12, 20])

In [23]:
holiday = pickle.load(open("../data/is_holiday.pkl", "rb"))

In [36]:
import numpy as np
a = np.zeros((40,5))
a[20:].shape

(20, 5)

In [24]:
holiday = torch.tensor(holiday, dtype = torch.)
holiday = holiday.repeat(12,1)

In [29]:
holiday[:, x_idx[-1]+1].shape

torch.Size([12])

In [5]:
sales_data.shape

torch.Size([730, 5, 12])

In [8]:
sales_data[x_idx, store_idx].shape

torch.Size([20, 12])

In [217]:
sales_data = pickle.load(open("../data/sales_data.pkl", "rb"))

In [171]:
sales_data.shape

torch.Size([730, 5, 759])

In [173]:
sales_data[0].shape

torch.Size([5, 759])

In [212]:
torch.set_printoptions(precision=10)

In [243]:
sales_data[:,:,301]

tensor([[-0.2907964289, -0.2907964289, -0.2907964289, -0.2907964289,
         -0.2907964289],
        [-0.2907964289, -0.2907964289, -0.2907964289, -0.2907964289,
         -0.2907964289],
        [-0.2907964289, -0.2907964289, -0.2907964289, -0.2907964289,
         -0.2907964289],
        ...,
        [-0.2907964289, -0.2907964289, -0.2907964289,  5.1843986511,
          2.4468011856],
        [-0.2907964289, -0.2907964289,  1.0780023336,  2.4468011856,
          1.0780023336],
        [ 1.0780023336, -0.2907964289,  1.0780023336,  1.0780023336,
          1.0780023336]])

In [175]:
from numpy import zeros, newaxis

In [183]:
a = zeros((6, 8))

In [244]:
lalala = np.dstack((sales_data[:,:,300],sales_data[:,:,301]))

In [246]:
lalala.shape

(3650, 759)

In [245]:
lalala[:,:,301]

IndexError: too many indices for array

In [194]:
b[:, :, 1] = a[:, :, newaxis]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [68]:
sales_data[:, :, 0] + sales_data[:, :, 1] 

tensor([[-0.5816, -0.5816, -0.5816, -0.5816,  2.1560],
        [-0.5816, -0.5816,  0.7872, -0.5816, -0.5816],
        [-0.5816, -0.5816, -0.5816, -0.5816,  0.7872],
        ...,
        [-0.5816, -0.5816, -0.5816, -0.5816, -0.5816],
        [-0.5816, -0.5816, -0.5816, -0.5816, -0.5816],
        [-0.5816, -0.5816, -0.5816, -0.5816, -0.5816]])

In [8]:
commodity_codes = pickle.load(open("../data/commodity_codes.pkl", "rb"))

In [66]:
len(commodity_codes)

759

In [105]:
list(commodity_codes)

[1810433,
 1761286,
 1970188,
 1923086,
 940047,
 1810447,
 1970192,
 1923090,
 1810451,
 940065,
 1810465,
 1970215,
 940079,
 1810479,
 1210417,
 1210421,
 1761345,
 940106,
 610379,
 1810506,
 940110,
 1413198,
 1761359,
 1810510,
 1761363,
 1413207,
 940124,
 1411164,
 1413225,
 940138,
 1810542,
 1831029,
 1413239,
 1923195,
 1810556,
 940156,
 1810560,
 1970306,
 1413257,
 1550473,
 1413261,
 1413275,
 940188,
 1810588,
 1970338,
 1413289,
 633012,
 1411255,
 1870017,
 1413316,
 610501,
 1870021,
 1970374,
 1810633,
 610515,
 1210580,
 1870035,
 1411291,
 1810651,
 610529,
 1210594,
 1870049,
 610533,
 1761509,
 1870053,
 1810665,
 710890,
 610547,
 930036,
 1870067,
 1413366,
 1870071,
 610551,
 710909,
 1923331,
 1870085,
 1810697,
 610579,
 1870099,
 1810710,
 1870108,
 1311007,
 1870112,
 1810724,
 610597,
 930086,
 1530156,
 610606,
 1870126,
 1530160,
 1411378,
 1870130,
 1411382,
 1810742,
 930109,
 1870144,
 930113,
 930127,
 1870162,
 1810774,
 1550687,
 610656,
 930145,

In [16]:
import numpy as np
import pandas as pd

In [20]:
main = pd.read_csv("../data/商品主檔.txt", sep = '\t')

In [21]:
main

原始店號             商品名稱     商品代號  品番   群番 有效期限     進貨成本  銷售價格       品牌  \
0       1205        和風昆布吻仔魚飯糰   617008   6   61   D1    18.28    32      飯糰屋   
1       1205         日式稻荷味付飯糰   610779   6   61   D1    21.33    35      飯糰屋   
2       1205             肉鬆飯糰   610501   6   61   D1    12.80    23      飯糰屋   
3       1205             鮪魚飯糰   610515   6   61   D1    13.33    25      飯糰屋   
4       1205           鮑菇脆筍飯糰   610010   6   61   D1    13.42    25      飯糰屋   
5       1205    玉米火腿蛋沙拉飯糰（北區）   611834   6   61   D1    14.28    25      飯糰屋   
6       1205          泰式打拋豬飯糰   610533   6   61   D1    16.26    28      飯糰屋   
7       1205         一配鹽蔥燒肉飯糰   611016   6   61   D1    17.14    30      飯糰屋   
8       1205     明太子龍蝦風味飯糰（區）   619937   6   61   D1    17.71    30      飯糰屋   
9       1205            大稻荷飯糰   610674   6   61   D1    17.42    30       飯糰   
10      1205          五目溏心蛋飯糰   610747   6   61   D1    20.33    35      飯糰屋   
11      1205        糖醋雞肉飯糰－北區   613331   6   61   D1    13.56    25      飯糰屋   
12      1205          炙燒培根卷飯糰   610733   6   61   D1    20.00    35      飯糰屋   
13      1205       柚香珠貝海鮮沙拉飯糰   619064   6   61   D1    19.82    35      飯糰屋   
14      1205          明太子鮭魚飯糰   619050   6   61   D1    19.82    35      飯糰屋   
15      1205        ＸＯ醬干貝拌飯飯糰   619032   6   61   D1    24.79    42      飯糰屋   
16      1205         韓式辣雞起司飯糰   619028   6   61   D1    23.99    42      飯糰屋   
17      1205           鮭魚起司飯糰   617012   6   61   D1    20.00    35      飯糰屋   
18      1205           鮭魚起司飯糰   610660   6   61   D1    17.42    30      飯糰屋   
19      1205         懷石烤蒲燒鰻飯糰   610529   6   61   D1    24.13    39      飯糰屋   
20      1205           柚香珠貝飯糰   611575   6   61   D1    20.33    35      飯糰屋   
21      1205        一配北海道秋鮭飯糰   611557   6   61   D1    20.16    35      飯糰屋   
22      1205          鮭魚鮭魚卵飯糰   611466   6   61   D1    23.33    35      飯糰屋   
23      1205          傳統香腸蛋飯糰   611452   6   61   D1    23.17    35      飯糰屋   
24      1205        明太子龍蝦風味飯糰   611393   6   61   D1    16.53    28      飯糰屋   
25      1205       一配懷石蒲燒鰻魚飯糰   616016   6   61   D1    24.13    39      飯糰屋   
26      1205          壽喜燒牛肉飯糰   610379   6   61   D1    16.27    28      飯糰屋   
27      1205        京醬肉絲飯糰－北區   612612   6   61   D1    14.05    25      飯糰屋   
28      1205           炭火烤雞飯糰   610088   6   61   D1    16.27    28      飯糰屋   
29      1205        日式茄汁太陽蛋飯糰   610729   6   61   D1    20.00    35      飯糰屋   
...      ...              ...      ...  ..  ...  ...      ...   ...      ...   
22645  12236          鮮醇果榨　檸檬  6160796  61  616  M12    32.66    49    ＡＳＡＨＩ   
22646  12236    －１９６雞尾酒＜櫻花櫻桃＞  6160564  61  616  M12    32.89    47      三得利   
22647  12236  調情聖手萬聖節期間限定蘭姆柳橙  6160932  61  616  M12    32.68    49    ＡＳＡＨＩ   
22648  12236     調情聖手萬聖節哈密瓜香草  6160928  61  616  M12    32.68    49    ＡＳＡＨＩ   
22649  12236         －１９６秋收葡萄  6160914  61  616  M12    32.89    49      三得利   
22650  12236   鮮摘果實　期間限定　直七柑橘  6161015  61  616  M12    54.07    79    ＡＳＡＨＩ   
22651  12236     調情聖手聖誕節限定黑醋栗  6160964  61  616  M12    32.68    49    ＡＳＡＨＩ   
22652  12236    Ｓｏｕｒ３沙瓦　水蜜桃風味  6160978  61  616  M12    30.94    49    ＳＯＵＲ３   
22653  12236       Ｓｏｕｒ３沙瓦　蘋果  6160982  61  616  M12    30.94    49    ＳＯＵＲ３   
22654  12236        微醉冬日蜜柑雞尾酒  6160996  61  616  M12    32.89    49      三得利   
22655  12236        微醉葡萄沙瓦雞尾酒  6160146  61  616  M14    32.95    47      三得利   
22656  12236        微醉白色沙瓦雞尾酒  6160423  61  616  M14    32.95    47      三得利   
22657  12236         莎瓦納頂級蘋果酒  6160623  61  616  M18    59.36    79  ｓａｖａｎｎａ   
22658  12236        思美洛ＩＣＥ青蘋果  6160619  61  616   Y1    41.38    65      思美洛   
22659  12236          冰火檸檬伏特加  6160441  61  616   Y1    29.98    50       冰火   
22660  12236          冰火葡萄伏特加  6160455  61  616   Y1    29.98    50       冰火   
22661  12236           冰火金黃香檳  6160469  61  616   Y1    29.98    50       冰火   
22662  12236        ＫＩＲＩＮ本榨柳橙  6160487  61  616   Y1    34.83    49       麒麟   
22663  1

In [50]:
group_data = main[['商品代號', '品番', '群番']].values
group_data = np.unique(group_data, axis = 0)
print(len(group_data))

4535


In [39]:
p = main[['品番']].values
p = np.unique(p)
print(len(p))

23


In [40]:
c = main[['群番']].values
c = np.unique(c)
print(len(c))

124


In [48]:
group_data = main[['商品代號', '品番', '群番']].values
group_data = np.unique(group_data, axis = 0)

In [49]:
group_data

array([[ 610010,       6,      61],
       [ 610038,       6,      61],
       [ 610042,       6,      61],
       ...,
       [6180118,      61,     618],
       [6180122,      61,     618],
       [6180136,      61,     618]], dtype=int64)

In [57]:
commodity_codes2p = {}
commodity_codes2c = {}
for group in group_data:
    commodity_codes2p[group[0]] = group[1]
    commodity_codes2c[group[0]] = group[2]

In [56]:
commodity_codes2[1810433]

181

In [58]:
com2p = []
com2c = []
for code in commodity_codes:
    com2p.append(commodity_codes2p[code])
    com2c.append(commodity_codes2c[code])    

In [60]:
len(np.unique(com2c))

37

In [61]:
len(np.unique(com2p))

12

In [146]:
sales_data[:, :, i]

tensor([[-0.2908, -0.2908, -0.2908, -0.2908, -0.2908],
        [-0.2908, -0.2908, -0.2908, -0.2908, -0.2908],
        [-0.2908, -0.2908, -0.2908, -0.2908, -0.2908],
        ...,
        [ 2.4468,  1.0780,  1.0780, -0.2908,  1.0780],
        [ 1.0780,  1.0780, -0.2908,  2.4468,  3.8156],
        [ 2.4468,  1.0780,  2.4468,  3.8156,  3.8156]])

In [148]:
np.array(sales_data[:, :, i].tolist()).reshape((730, 5))

array([[-0.29079643, -0.29079643, -0.29079643, -0.29079643, -0.29079643],
       [-0.29079643, -0.29079643, -0.29079643, -0.29079643, -0.29079643],
       [-0.29079643, -0.29079643, -0.29079643, -0.29079643, -0.29079643],
       ...,
       [ 2.44680119,  1.07800233,  1.07800233, -0.29079643,  1.07800233],
       [ 1.07800233,  1.07800233, -0.29079643,  2.44680119,  3.81559992],
       [ 2.44680119,  1.07800233,  2.44680119,  3.81559992,  3.81559992]])

In [121]:
sales_data = sales_data.tolist()

In [126]:
len(sales_data[0][0])

759

In [149]:
processed_sales_data_p_dict = {}
processed_sales_data_c_dict = {}
commodity_codes_list = list(commodity_codes)
for i in range(len(commodity_codes_list)):
    if commodity_codes2p[commodity_codes_list[i]] not in processed_sales_data_p_dict:
        processed_sales_data_p_dict[commodity_codes2p[commodity_codes_list[i]]] = np.array(sales_data[:, :, i].tolist()).reshape((730, 5))
    else:
        processed_sales_data_p_dict[commodity_codes2p[commodity_codes_list[i]]] += np.array(sales_data[:, :, i].tolist()).reshape((730, 5))
    if commodity_codes2c[commodity_codes_list[i]] not in processed_sales_data_c_dict:
        processed_sales_data_c_dict[commodity_codes2c[commodity_codes_list[i]]] = np.array(sales_data[:, :, i].tolist()).reshape((730, 5))
    else:
        processed_sales_data_c_dict[commodity_codes2c[commodity_codes_list[i]]] += np.array(sales_data[:, :, i].tolist()).reshape((730, 5))

In [267]:
processed_sales_data_p_dict[17]

array([[-14.21377864, -12.84497997, -14.21377873, -12.84497997,
        -10.10738227],
       [-15.5825775 , -18.32017502, -15.5825775 , -15.5825775 ,
        -11.47618112],
       [-10.10738236, -12.84497997, -16.95137626, -16.95137626,
        -12.84497997],
       ...,
       [-16.95137626, -16.95137626, -15.5825775 , -16.95137626,
        -15.5825775 ],
       [-18.32017502, -18.32017502, -14.21377864, -18.32017502,
        -16.95137626],
       [-15.58257741, -15.5825775 , -16.95137626, -16.95137626,
        -16.95137626]])

In [249]:
haha2 = np.dstack(processed_sales_data_p_dict.values())

c:\users\v-erhuan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [259]:
haha2[:,:,1]

tensor([[-14.2137784958, -12.8449802399, -14.2137784958, -12.8449802399,
         -10.1073818207],
        [-15.5825777054, -18.3201751709, -15.5825777054, -15.5825777054,
         -11.4761810303],
        [-10.1073827744, -12.8449802399, -16.9513759613, -16.9513759613,
         -12.8449802399],
        ...,
        [-16.9513759613, -16.9513759613, -15.5825777054, -16.9513759613,
         -15.5825777054],
        [-18.3201751709, -18.3201751709, -14.2137784958, -18.3201751709,
         -16.9513759613],
        [-15.5825777054, -15.5825777054, -16.9513759613, -16.9513759613,
         -16.9513759613]])

In [251]:
haha2.shape

(730, 5, 12)

In [150]:
haha = [k for k in processed_sales_data_p_dict.values()]

In [169]:
haha[0]

tensor([[  2.6788,  -6.9028, -24.6971,  -4.1652,  -0.0588],
        [ -0.0588,  -9.6404, -21.9595,  -2.7964,  -2.7964],
        [  8.1540,   9.5228, -24.6971,  14.9980,   2.6788],
        ...,
        [ -0.0588,  10.8916, -16.4843,  -2.7964,  -2.7964],
        [  9.5228,   9.5228, -16.4843,   1.3100,   5.4164],
        [  8.1540,   1.3100, -26.0659,  -6.9028,  -1.4276]])

In [170]:
haha.shape

torch.Size([12, 730, 5])

In [269]:
import torch

# haha = torch.tensor(haha, dtype=torch.float)
haha2 = torch.tensor(haha2, dtype=torch.float)

c:\users\v-erhuan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.


In [253]:
haha.view(730, 5, -1).shape

torch.Size([730, 5, 12])

In [166]:
haha.view(730, 5, -1)[:, :, 0]

tensor([[  2.6788, -24.6971,   5.4164,   5.4164,  -0.0588],
        [ 17.7356, -15.1155,  -2.7964,   8.1540,  -8.2716],
        [  6.7852, -11.0092,  -5.5340,   2.6788, -19.2219],
        ...,
        [ 16.0702,  -5.8306,  -8.5682,  16.0702,  14.7014],
        [ 13.3326,  -9.9370,  -8.5682,  10.5950,  14.7014],
        [ 11.9638,  -5.8306,  -0.3554,  20.1766,   9.2262]])

In [254]:
haha2.shape

torch.Size([730, 5, 12])

In [268]:
haha2[:,:,1]
# [  2.67883509,  -6.90275666, -24.69714081,  -4.16515839,
#           -0.05876264],
# [ -0.05876276,  -9.64035419, -21.95954329,  -2.79636014,
#          -2.79636028]
# array([[  2.67883509,  -6.90275666, -24.69714081,  -4.16515839,
#          -0.05876264],
#        [ -0.05876276,  -9.64035419, -21.95954329,  -2.79636014,
#          -2.79636028],
#        [  8.15403011,   9.52282879, -24.69714075,  14.99802479,
#           2.67883489],
#        ...,
#        [ -0.05876285,  10.89162758, -16.48434815,  -2.79636043,
#          -2.79636034],
#        [  9.52282935,   9.5228287 , -16.48434824,   1.31003666,
#           5.41643295],
#        [  8.15403029,   1.31003621, -26.06593952,  -6.90275657,
#          -1.42756128]])

tensor([[-14.2137784958, -12.8449802399, -14.2137784958, -12.8449802399,
         -10.1073818207],
        [-15.5825777054, -18.3201751709, -15.5825777054, -15.5825777054,
         -11.4761810303],
        [-10.1073827744, -12.8449802399, -16.9513759613, -16.9513759613,
         -12.8449802399],
        ...,
        [-16.9513759613, -16.9513759613, -15.5825777054, -16.9513759613,
         -15.5825777054],
        [-18.3201751709, -18.3201751709, -14.2137784958, -18.3201751709,
         -16.9513759613],
        [-15.5825777054, -15.5825777054, -16.9513759613, -16.9513759613,
         -16.9513759613]])